#%RAML 1.0
title: LMSka API
version: 1.0
baseUri: https://a.lmska.com/api
description: © 2022. LMSka - Learning Managment System by Axonax

uses:
  assets: assets.lib.raml

/register:
  displayName: Register
  description: Register in LMSka
  post:
    is: [ assets.paging]
    description: Register in LMSka
    queryParameters:
      email:
        type: string
        description: Email address
        required: true
        example: V@rte.im
      password:
        type: string
        description: Password
        required: true
        example: 123456
      telephone_number:
        type: string
        description: Phone number
        required: true
        example: 0980009999
      telephone_code:
        type: string
        description: Phone number
        required: true
        example: +38
      first_name:
        type: string
        description: First Name
        required: true
        example: John
      last_name:
        type: string
        description: Last Name
        required: true
        example: Doe
      role_id:
        type: int
        description: Role ID
        required: true
        example: 5 (Student)
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                success: true
                message: User was successfully registered but not verified
/auth:
  displayName: Auth
  description: Login in LMSka  
  put:
    is: [ assets.paging]
    description: Login in LMSka
    queryParameters:
      email:
        type: string
        description: Account email
        required: true
        example: V@rte.im
      password:
        type: string
        description: Account password
        required: true
        example: 123456      
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYS5sbXNrYS5jb21cL2FwaVwvYXV0aCIsImlhdCI6MTY0OTE1NzEwNywiZXhwIjoxNjQ5MjQzNTA3LCJuYmYiOjE2NDkxNTcxMDcsImp0aSI6IktZWXJQMnp1TWxIdVBHSlEiLCJzdWIiOjEsInBydiI6IjYwNjU4YTI4ZDVmM2ZhODNlMTZiNTIxY2M3YzM0NTI2YjAwMTFiYTYifQ.H4RmhOKIOpXO8qVbqCOQ9mbEqXZbMP8vC6zNcbJOEgs
                permissions:
                - id: 1
                  name: Can see detail of the course
                  permission: can_show_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 2
                  name: Can see all courses
                  permission: can_index_courses
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 3
                  name: Can delete the course
                  permission: can_destroy_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 4
                  name: Can create the new course
                  permission: can_store_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 5
                  name: Can update the existing course
                  permission: can_update_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 6
                  name: Can attach user to course
                  permission: can_attach_user_to_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 7
                  name: Can detach user from course
                  permission: can_detach_user_from_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 8
                  name: Can update profile
                  permission: can_update_profile
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 9
                  name: Can show profile
                  permission: can_show_profile
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 10
                  name: Can store user
                  permission: can_store_user
                  group:
                    id: 4
                    name: Users
                    group: user
                - id: 11
                  name: Can update user
                  permission: can_update_user
                  group:
                    id: 4
                    name: Users
                    group: user
                - id: 12
                  name: Can destroy user
                  permission: can_destroy_user
                  group:
                    id: 4
                    name: Users
                    group: user
                - id: 13
                  name: Can show user
                  permission: can_show_user
                  group:
                    id: 4
                    name: Users
                    group: user
                - id: 14
                  name: Can see all users
                  permission: can_index_users
                  group:
                    id: 4
                    name: Users
                    group: user
                - id: 15
                  name: Can change user password
                  permission: can_change_user_password
                  group:
                    id: 4
                    name: Users
                    group: user
                - id: 16
                  name: Can change user active status
                  permission: can_change_user_activation_status
                  group:
                    id: 4
                    name: Users
                    group: user
                - id: 17
                  name: Can update course ticket
                  permission: can_update_course_ticket
                  group:
                    id: 10
                    name: Course ticket group
                    group: ticket
                - id: 18
                  name: Can destroy course ticket
                  permission: can_destroy_course_ticket
                  group:
                    id: 10
                    name: Course ticket group
                    group: ticket
                - id: 19
                  name: Can index course tickets
                  permission: can_index_course_tickets
                  group:
                    id: 10
                    name: Course ticket group
                    group: ticket
                - id: 20
                  name: Can generate course ticket holder pdf sticker
                  permission: can_generate_course_ticket_holder_pdf_sticker
                  group:
                    id: 15
                    name: Course ticket holder
                    group: course_ticket_holder
                - id: 21
                  name: Can show course ticket schema
                  permission: can_show_course_ticket_schema
                  group:
                    id: 5
                    name: Course ticket schemas
                    group: course_ticket_schema
                - id: 22
                  name: Can index course ticket schemas
                  permission: can_index_course_ticket_schemas
                  group:
                    id: 5
                    name: Course ticket schemas
                    group: course_ticket_schema
                - id: 23
                  name: Can destroy course ticket schema
                  permission: can_destroy_course_ticket_schema
                  group:
                    id: 5
                    name: Course ticket schemas
                    group: course_ticket_schema
                - id: 24
                  name: Can store course ticket schema
                  permission: can_store_course_ticket_schema
                  group:
                    id: 5
                    name: Course ticket schemas
                    group: course_ticket_schema
                - id: 25
                  name: Can update course ticket schema
                  permission: can_update_course_ticket_schema
                  group:
                    id: 5
                    name: Course ticket schemas
                    group: course_ticket_schema
                - id: 26
                  name: Can restore course ticket schema
                  permission: can_restore_course_ticket_schema
                  group:
                    id: 5
                    name: Course ticket schemas
                    group: course_ticket_schema
                - id: 27
                  name: Can attach options to ticket schema
                  permission: can_attach_options_to_ticket_schema
                  group:
                    id: 5
                    name: Course ticket schemas
                    group: course_ticket_schema
                - id: 28
                  name: Can detach options from ticket schema
                  permission: can_detach_options_to_ticket_schema
                  group:
                    id: 5
                    name: Course ticket schemas
                    group: course_ticket_schema
                - id: 29
                  name: Can store course ticket schema option
                  permission: can_store_course_ticket_schema_option
                  group:
                    id: 6
                    name: Course ticket schema options
                    group: course_ticket_schema_option
                - id: 30
                  name: Can update course ticket schema option
                  permission: can_update_course_ticket_schema_option
                  group:
                    id: 6
                    name: Course ticket schema options
                    group: course_ticket_schema_option
                - id: 31
                  name: Can index course ticket schema options
                  permission: can_index_course_ticket_schema_options
                  group:
                    id: 6
                    name: Course ticket schema options
                    group: course_ticket_schema_option
                - id: 32
                  name: Can destroy course ticket schema option
                  permission: can_destroy_course_ticket_schema_option
                  group:
                    id: 6
                    name: Course ticket schema options
                    group: course_ticket_schema_option
                - id: 33
                  name: Can store course ticket schema price by count
                  permission: can_store_course_ticket_schema_price_by_count
                  group:
                    id: 7
                    name: Course ticket schema price by count group
                    group: course_ticket_schema_ticket_by_price
                - id: 34
                  name: Can index course ticket schema prices by count
                  permission: can_index_course_ticket_schema_prices_by_count
                  group:
                    id: 7
                    name: Course ticket schema price by count group
                    group: course_ticket_schema_ticket_by_price
                - id: 35
                  name: Can destroy course ticket schema price by count
                  permission: can_destroy_course_ticket_schema_price_by_count
                  group:
                    id: 7
                    name: Course ticket schema price by count group
                    group: course_ticket_schema_ticket_by_price
                - id: 36
                  name: Can store course ticket schema price by datetime
                  permission: can_store_course_ticket_schema_price_by_datetime
                  group:
                    id: 8
                    name: Course ticket schema price by datetime group
                    group: course_ticket_schema_ticket_by_datetime
                - id: 37
                  name: Can index course ticket schema prices by datetime
                  permission: can_index_course_ticket_schema_prices_by_datetime
                  group:
                    id: 8
                    name: Course ticket schema price by datetime group
                    group: course_ticket_schema_ticket_by_datetime
                - id: 38
                  name: Can destroy course ticket schema price by datetime
                  permission: can_destroy_course_ticket_schema_price_by_datetime
                  group:
                    id: 8
                    name: Course ticket schema price by datetime group
                    group: course_ticket_schema_ticket_by_datetime
                - id: 39
                  name: Can store course order
                  permission: can_store_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 40
                  name: Can show course order
                  permission: can_show_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 41
                  name: Can make course order report
                  permission: can_make_course_order_report
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 42
                  name: Can update course order
                  permission: can_update_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 43
                  name: Can destroy course order
                  permission: can_destroy_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 44
                  name: Can index course orders
                  permission: can_index_course_orders
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 45
                  name: Can store promo code
                  permission: can_store_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 46
                  name: Can show promo code
                  permission: can_show_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 47
                  name: Can update promo code
                  permission: can_update_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 48
                  name: Can destroy promo code
                  permission: can_destroy_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 49
                  name: Can index promo codes
                  permission: can_index_promo_code_orders
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 50
                  name: Can store course ticket
                  permission: can_store_course_ticket
                  group:
                    id: 10
                    name: Course ticket group
                    group: ticket
                - id: 51
                  name: Can restore course ticket
                  permission: can_restore_course_ticket
                  group:
                    id: 10
                    name: Course ticket group
                    group: ticket
                - id: 52
                  name: Can store course ticket form
                  permission: can_store_course_form
                  group:
                    id: 12
                    name: Course form group
                    group: course_form
                - id: 53
                  name: Can update course form
                  permission: can_update_course_form
                  group:
                    id: 12
                    name: Course form group
                    group: course_form
                - id: 54
                  name: 'Can destroy course form '
                  permission: can_destroy_course_form
                  group:
                    id: 12
                    name: Course form group
                    group: course_form
                - id: 55
                  name: Can show form
                  permission: can_show_course_form
                  group:
                    id: 12
                    name: Course form group
                    group: course_form
                - id: 56
                  name: Can store course payment system for fondy
                  permission: can_store_payment_system_fondy
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 57
                  name: Can update course payment system for fondy
                  permission: can_update_payment_system_fondy
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 58
                  name: Can destroy course payment system for fondy
                  permission: can_destroy_payment_system_fondy
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 59
                  name: Can show course payment system for fondy
                  permission: can_show_payment_system_fondy
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 60
                  name: Can store course payment system for liqpay
                  permission: can_store_payment_system_liqpay
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 61
                  name: Can update course payment system for liqpay
                  permission: can_update_payment_system_liqpay
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 62
                  name: Can destroy course payment system for liqpay
                  permission: can_destroy_payment_system_liqpay
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 63
                  name: Can show course payment system for liqpay
                  permission: can_show_payment_system_liqpay
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 64
                  name: Can store course payment system for wayforpay
                  permission: can_store_payment_system_wayforpay
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 65
                  name: Can update course payment system for wayforpay
                  permission: can_update_payment_system_wayforpay
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 66
                  name: Can destroy course payment system for wayforpay
                  permission: can_destroy_payment_system_wayforpay
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 67
                  name: Can show course payment system for wayforpay
                  permission: can_show_payment_system_wayforpay
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 68
                  name: Can show course payment system for non-cash
                  permission: can_show_payment_system_non-cash
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 69
                  name: Can destroy course payment system for non-cash
                  permission: can_destroy_payment_system_non-cash
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 70
                  name: Can update course payment system for non-cash
                  permission: can_update_payment_system_non-cash
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 71
                  name: Can store course payment system for non-cash
                  permission: can_store_payment_system_non-cash
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 72
                  name: Can receive all payment systems
                  permission: can_index_payment_systems
                  group:
                    id: 13
                    name: Course payment system group
                    group: course_payment_system_group
                - id: 73
                  name: Can store course ticket holder check in
                  permission: can_store_course_ticket_holder_check_in
                  group:
                    id: 14
                    name: Course ticket holder check in group
                    group: check_in
                - id: 74
                  name: Can update course ticket holder check in
                  permission: can_update_course_ticket_holder_check_in
                  group:
                    id: 14
                    name: Course ticket holder check in group
                    group: check_in
                - id: 75
                  name: Can print course ticket holder check in
                  permission: can_print_course_ticket_holder_check_ins
                  group:
                    id: 14
                    name: Course ticket holder check in group
                    group: check_in
                - id: 76
                  name: Can destroy course ticket holder check in
                  permission: can_destroy_course_ticket_holder_check_in
                  group:
                    id: 14
                    name: Course ticket holder check in group
                    group: check_in
                - id: 77
                  name: Can show course ticket holder check in
                  permission: can_show_course_ticket_holder_check_in
                  group:
                    id: 14
                    name: Course ticket holder check in group
                    group: check_in
                - id: 78
                  name: Can receive all course ticket holder check ins
                  permission: can_index_course_ticket_holder_check_ins
                  group:
                    id: 14
                    name: Course ticket holder check in group
                    group: check_in
                email: v@rte.im
                first_name: Vetaska
                last_name: Муди
                telephone_code: '380'
                telephone_number: '678455588'
                is_check_in: 1
                is_print_sticker: 1
                role:
                  id: 1
                  name: Administrator
                  role: admin
                id: 1
                zones: []
                user_hash:
                print_servers:
                  data: []
                course_settings: []
                scan_mode: 0
/forgotPassword:
  displayName: Forgot password?
  description: Restore forgot password in LMSka  
  post:
    is: [ assets.paging]
    description: Restore password in LMSka
    queryParameters:
      email:
        type: string
        description: Account email
        required: true
        example: V@rte.im  
      is_staff:
        type: bool
        description: default
        required: true
        example: false     
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                message: "Undefined constant App\\Models\\Api\\UserRole::CUSTOMER (View: /var/www/Lmska/backend/resources/views/email/api/user/forgot-password.blade.php)"
/courses:
  displayName: Courses
  description: Get courses data in LMSka
  get:
    is: [ assets.paging]
    description: Get courses data in LMSka  
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                data:
                - id: 2
                  title: Тестовый курс
                  description: "<p>Описание для тестового курса</p>"
                  address: online
                  address_lat:
                  address_lng:
                  registration_start: '2021-12-31 13:11:00'
                  registration_end: '2025-12-31 13:11:00'
                  course_start: '2021-12-31 13:11:00'
                  course_end: '2025-12-31 13:11:00'
                  owner:
                    id: 3
                    first_name: Андрей
                    last_name: Голуб
                    avatar: https://a.lmska.com/storage/users/3/magnar.jpeg
                    telephone_code: '380'
                    telephone_number: '676654620'
                    company:
                    email: a@rte.im
                    role:
                      id: 1
                      name: Administrator
                      role: admin
                  setting:
                    status:
                      id: 2
                      name: Active
                      status: active
                    payment_currency:
                      id: 1
                      name: Ukrainian Hryvnia
                      currency: hryvnia
                      iso_code: uah
                    check_in:
                    facebook_pixel:
                    yandex_metrika_id:
                    google_conversion_id:
                    google_tag_manager_id:
                    fix_commission: '0.000'
                    percent_commission: '0.00'
                    self_system_commission_included_payment: true
                    payment_system_commission_included_payment: true
                    payment_activated: true
                    lesson_schema_graph: "[]"
                    use_lesson_schema_graph: 0
                  logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                  logo_type: png
                  subway_station:
                  location_name:
                  created_at: '2021-12-31T11:11:57.000000Z'
                  updated_at: '2022-04-05T07:32:06.000000Z'
                  fill_step:
                    id: 1
                    main_setting_step: 1
                    ticket_schema_step: 1
                    mail_test_step: 0
                    register_form_step: 1
                    site_course_step: 1
                    payment_method_step: 1
                    course_id: 2
                    created_at: '2021-12-31T11:11:58.000000Z'
                    updated_at: '2022-04-07T10:47:09.000000Z'
                    promo_codes_step: 0
                    streaming_links_step: 0
                  statistics: []
                  finances: []
                  stream_schemas: []
                  fee: ''
/courses/{id}/lessons:
  displayName: Lessons of Course
  description: Get lessons data of courses in LMSka
  get:
    is: [ assets.paging]
    description: Get lessons data of courses in LMSka
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                data:
                - id: 14
                  title: Второй урок
                  description:
                  category_text:
                  content:
                  - id: 608
                    position: 0
                    content: '{"id": "431387450818584", "type": "video", "hidden": false, "preview":
                      "https://a.lmska.com/storage/course/previews/video.png", "video_url": "materials/2/3.
                      HTML теги (теория).mp4"}'
                    lesson_id: 14
                    deleted_at:
                    created_at:
                    updated_at:
                  lesson_start:
                  lesson_end:
                  is_demo: 1
                  is_stop: 0
                  is_homework: 1
                  is_video_lesson: 0
                  test:
                    id: 9
                    creator_id: 3
                    deleted_at:
                    created_at: '2022-01-31T10:56:49.000000Z'
                    updated_at: '2022-01-31T10:56:49.000000Z'
                    lesson_id: 14
                    course_id:
                    homework_id: 4
                    start_time:
                    end_time:
                    total_score: 0
                    visible: 1
                    shuffle: 0
                  ticket_schemas:
                  - id: 1
                    title: Standart
                    description: test12
                    original_price: '5.000'
                    price: '5.000'
                    color: "#000000"
                    type:
                      id: 2
                      name: Online
                      type: online
                    moderation_type:
                      id: 1
                      name: Auto
                      type: auto
                    available_amount: -6
                    all_available_amount: 1
                    max_amount_per_order: 1
                    min_amount_per_order: 1
                    options: []
                    start_sale: '2021-12-31 13:11:00'
                    end_sale: '2025-12-31 13:11:00'
                    created_at: '2021-12-31T11:11:58.000000Z'
                    updated_at: '2022-04-01T15:03:02.000000Z'
                    deleted_at:
                    ticket_email_text:
                    status: 1
                    position: 0
                    time_data: []
                  - id: 3
                    title: Standart2
                    description: test
                    original_price: '9.000'
                    price: '9.000'
                    color: "#fb0909"
                    type:
                      id: 2
                      name: Online
                      type: online
                    moderation_type:
                      id: 1
                      name: Auto
                      type: auto
                    available_amount: 1
                    all_available_amount: 1
                    max_amount_per_order: 1
                    min_amount_per_order: 1
                    options: []
                    start_sale: '2022-01-23 00:00:00'
                    end_sale: '2026-01-31 23:59:59'
                    created_at: '2022-01-24T11:06:12.000000Z'
                    updated_at: '2022-04-01T14:07:06.000000Z'
                    deleted_at:
                    ticket_email_text:
                    status: 1
                    position: 1
                    time_data: []
                  position: 0
                  user_info:
                    mark:
                    time_spent_in_seconds:
                  comment_count: 0
                  rates:
                    average_rate: 5
                    count: 1
                    rate_weight: '{"5":100,"4":0,"3":0,"2":0,"1":0}'
/users/courses:
  displayName: Users courses
  description: Get users courses in LMSka
  get:
    is: [ assets.paging]
    description: Get users courses in LMSka
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                data:
                  '0':
                    id: 7
                    title: Материалы RegToEVENT
                    description: "<p>Ознакомительный курс про RegToEVENT. Что это такое и чем оно
                      пригодится организаторам ивентов</p>"
                    address: online
                    address_lat:
                    address_lng:
                    registration_start: '2022-03-28 17:36:00'
                    registration_end: '2022-12-31 17:36:00'
                    course_start: '2022-03-31 15:13:00'
                    course_end: '2022-12-31 17:36:00'
                    owner:
                      id: 29
                      first_name: Люба
                      last_name: Любов
                      avatar: https://a.lmska.com/storage/default.png
                      telephone_code: '380'
                      telephone_number: '934561649'
                      company:
                      email: inforegtoevent@gmail.com
                      role:
                        id: 2
                        name: Owner
                        role: owner
                    setting:
                      status:
                        id: 2
                        name: Active
                        status: active
                      category:
                        id: 1
                        name: Conference
                        category: conference
                      subject:
                        id: 1
                        name: Informational technologies
                        subject: information_technologies
                      recount_currency:
                      payment_currency:
                        id: 1
                        name: Ukrainian Hryvnia
                        currency: hryvnia
                        iso_code: uah
                      check_in:
                      language:
                        id: 2
                        name: Ukrainian
                        language: ukrainian
                        iso_code: ua
                      country:
                        id: 1
                        name: Ukraine
                        country: ukraine
                        iso_code: ua
                        languages:
                        - id: 2
                          name: Ukrainian
                          language: ukrainian
                          iso_code: ua
                        - id: 3
                          name: Russian
                          language: russian
                          iso_code: ru
                        - id: 6
                          name: Hungarian
                          language: hungarian
                          iso_code: hu
                        - id: 7
                          name: Romanian
                          language: romanian
                          iso_code: ro
                        currencies:
                        - id: 1
                          name: Ukrainian Hryvnia
                          currency: hryvnia
                          iso_code: uah
                        - id: 4
                          name: Russian Ruble
                          currency: ruble
                          iso_code: rub
                      fix_commission: '0.000'
                      percent_commission: '0.00'
                      self_system_commission_included_payment: true
                      payment_system_commission_included_payment: true
                      payment_activated: true
                      ticket_description_top:
                      ticket_description_bottom:
                      contact_email:
                      is_contact_email_verified: 0
                      contact_phone:
                      contact_name:
                      offer_text:
                      affiliate_text:
                      registration_first_step_text: "\r\n    <p>EN:</p>\r\n<p>When registering for
                        the Материалы RegToEVENT course, you (or someone else) specified this email
                        as a contact email. An account has been created for you at <a href=\"https://c.lmska.net\">https://c.lmska.net</a>\r\nYou
                        can see your orders and change ticket data in your account on your own</p>\r\n<br/>\r\n<p>УК:</p>\r\n<p>При
                        реєстрації на подію Материалы RegToEVENT ви (або хтось інший) вказали цей
                        email як контактний. Вам був створений кабінет за адресою <a href=\"https://c.lmska.net\">https://c.lmska.net</a>\r\nВи
                        можете бачити ваші замовлення і міняти дані про квиток в кабінеті самостійно</p>\r\n<br/>\r\n<p>РУ:</p>\r\n<p>При
                        регистрации на событие Материалы RegToEVENT вы ( или кто то другой) указали
                        этот email как контактный. Вам был создан кабинет по адресу\r\n<a href=\"https://c.lmska.net\">https://c.lmska.net</a>\r\nВы
                        можете видеть ваши заказы и менять данные о билете в кабинете самостоятельно</p>"
                      ticket_with_text:
                      online_text:
                      course_url:
                      fb_link_group:
                      available_duplicate_contacts: 0
                      use_ticket_schema_emails: 0
                      lesson_schema_graph: '{"edges": {"edge11": {"source": "91", "target": "92"},
                        "edge12": {"source": "92", "target": "93"}, "edge_1": {"source": "81", "target":
                        "82"}, "edge_2": {"source": "82", "target": "83"}, "edge_3": {"source": "83",
                        "target": "85"}, "edge_4": {"source": "85", "target": "84"}, "edge_5": {"source":
                        "84", "target": "86"}, "edge_6": {"source": "87", "target": "88"}, "edge_7":
                        {"source": "88", "target": "89"}, "edge_8": {"source": "89", "target": "90"},
                        "edge_9": {"source": "90", "target": "91"}, "edge_10": {"source": "86", "target":
                        "87"}, "edge_11": {"source": "93", "target": "94"}, "edge_12": {"source":
                        "94", "target": "95"}, "edge_13": {"source": "95", "target": "96"}, "edge_14":
                        {"source": "96", "target": "97"}, "edge_15": {"source": "97", "target": "98"}},
                        "nodes": {"81": {"url": "/course/7/lessons/81", "name": "Что такое б\nилетный
                        опе\nратор", "radius": 88}, "82": {"url": "/course/7/lessons/82", "name":
                        "Что можно д\nелать с Reg\nToEVENT", "radius": 91}, "83": {"url": "/course/7/lessons/83",
                        "name": "Типы билетов в \nRegToEVENT", "radius": 77}, "84": {"url": "/course/7/lessons/84",
                        "name": "Апгрейд билета", "radius": 84}, "85": {"url": "/course/7/lessons/85",
                        "name": "Дополнительные \nопции", "radius": 77}, "86": {"url": "/course/7/lessons/86",
                        "name": "Расписание \nцен", "radius": 85}, "87": {"url": "/course/7/lessons/87",
                        "name": "Форма регис\nтрации", "radius": 85}, "88": {"url": "/course/7/lessons/88",
                        "name": "Интеграция \nформы", "radius": 85}, "89": {"url": "/course/7/lessons/89",
                        "name": "Оплата биле\nтов", "radius": 85}, "90": {"url": "/course/7/lessons/90",
                        "name": "Сайт событи\nя", "radius": 85}, "91": {"url": "/course/7/lessons/91",
                        "name": "Оформление \nбилета", "radius": 85}, "92": {"url": "/course/7/lessons/92",
                        "name": "Промокоды", "radius": 85}, "93": {"url": "/course/7/lessons/93",
                        "name": "Онлайн тран\nсляции", "radius": 84}, "94": {"url": "/course/7/lessons/94",
                        "name": "Чат-боты и \nрассылки", "radius": 88}, "95": {"url": "/course/7/lessons/95",
                        "name": "Роли пользо\nвателей", "radius": 88}, "96": {"url": "/course/7/lessons/96",
                        "name": "Дополнитель\nные возможн\nости", "radius": 85}, "97": {"url": "/course/7/lessons/97",
                        "name": "Возможные сценарии", "radius": 88}, "98": {"url": "/course/7/lessons/98",
                        "name": "Часто задаваемые \nвопросы", "radius": 85}, "101": {"url": "/course/7/lessons/101",
                        "name": "Первый. Фича...", "radius": 60}}, "layouts": {"nodes": {"81": {"x":
                        -180, "y": -190}, "82": {"x": 50, "y": -190}, "83": {"x": 270, "y": -190},
                        "84": {"x": 710, "y": -190}, "85": {"x": 480, "y": -190}, "86": {"x": 960,
                        "y": -190}, "87": {"x": 970, "y": 40}, "88": {"x": 720, "y": 40}, "89": {"x":
                        480, "y": 40}, "90": {"x": 260, "y": 40}, "91": {"x": 30, "y": 40}, "92":
                        {"x": -180, "y": 40}, "93": {"x": -180, "y": 280}, "94": {"x": 40, "y": 280},
                        "95": {"x": 260, "y": 280}, "96": {"x": 500, "y": 280}, "97": {"x": 730, "y":
                        280}, "98": {"x": 970, "y": 270}, "99": {"x": 1100, "y": 270}, "100": {"x":
                        1230, "y": 270}, "101": {"x": 1360, "y": 270}}}}'
                      use_lesson_schema_graph: 0
                    logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    logo_type: png
                    subway_station:
                    location_name:
                    created_at: '2022-03-28T14:44:08.000000Z'
                    updated_at: '2022-04-07T18:40:10.000000Z'
                    fill_step:
                      id: 5
                      main_setting_step: 1
                      ticket_schema_step: 1
                      mail_test_step: 0
                      register_form_step: 1
                      site_course_step: 1
                      payment_method_step: 1
                      course_id: 7
                      created_at: '2022-03-28T14:44:10.000000Z'
                      updated_at: '2022-04-07T18:40:42.000000Z'
                      promo_codes_step: 1
                      streaming_links_step: 0
                    statistics: []
                    finances: []
                    stream_schemas: []
                    fee: ''
                  '17':
                    id: 2
                    title: Тестовый курс
                    description: "<p>Описание для тестового курса</p>"
                    address: online
                    address_lat:
                    address_lng:
                    registration_start: '2021-12-31 13:11:00'
                    registration_end: '2025-12-31 13:11:00'
                    course_start: '2021-12-31 13:11:00'
                    course_end: '2025-12-31 13:11:00'
                    owner:
                      id: 3
                      first_name: Андрей
                      last_name: Голуб
                      avatar: https://a.lmska.com/storage/users/3/magnar.jpeg
                      telephone_code: '380'
                      telephone_number: '676654620'
                      company:
                      email: a@rte.im
                      role:
                        id: 1
                        name: Administrator
                        role: admin
                    setting:
                      status:
                        id: 2
                        name: Active
                        status: active
                      category:
                        id: 1
                        name: Conference
                        category: conference
                      subject:
                        id: 1
                        name: Informational technologies
                        subject: information_technologies
                      recount_currency:
                      payment_currency:
                        id: 1
                        name: Ukrainian Hryvnia
                        currency: hryvnia
                        iso_code: uah
                      check_in:
                      language:
                        id: 2
                        name: Ukrainian
                        language: ukrainian
                        iso_code: ua
                      country:
                        id: 1
                        name: Ukraine
                        country: ukraine
                        iso_code: ua
                        languages:
                        - id: 2
                          name: Ukrainian
                          language: ukrainian
                          iso_code: ua
                        - id: 3
                          name: Russian
                          language: russian
                          iso_code: ru
                        - id: 6
                          name: Hungarian
                          language: hungarian
                          iso_code: hu
                        - id: 7
                          name: Romanian
                          language: romanian
                          iso_code: ro
                        currencies:
                        - id: 1
                          name: Ukrainian Hryvnia
                          currency: hryvnia
                          iso_code: uah
                        - id: 4
                          name: Russian Ruble
                          currency: ruble
                          iso_code: rub
                      fix_commission: '0.000'
                      percent_commission: '0.00'
                      self_system_commission_included_payment: true
                      payment_system_commission_included_payment: true
                      payment_activated: true
                      ticket_description_top:
                      ticket_description_bottom:
                      contact_email:
                      is_contact_email_verified: 0
                      contact_phone:
                      contact_name:
                      offer_text:
                      affiliate_text:
                      registration_first_step_text: |2-

                            <p>EN:</p>
                        <p>When registering for the Тестовый курс course, you (or someone else) specified this email as a contact email. An account has been created for you at <a href="https://c.rte.im">https://c.rte.im</a>
                        You can see your orders and change ticket data in your account on your own</p>
                        <br/>
                        <p>УК:</p>
                        <p>При реєстрації на подію Тестовый курс ви (або хтось інший) вказали цей email як контактний. Вам був створений кабінет за адресою <a href="https://c.rte.im">https://c.rte.im</a>
                        Ви можете бачити ваші замовлення і міняти дані про квиток в кабінеті самостійно</p>
                        <br/>
                        <p>РУ:</p>
                        <p>При регистрации на событие Тестовый курс вы ( или кто то другой) указали этот email как контактный. Вам был создан кабинет по адресу
                        <a href="https://c.rte.im">https://c.rte.im</a>
                        Вы можете видеть ваши заказы и менять данные о билете в кабинете самостоятельно</p>
                      ticket_with_text:
                      online_text:
                      course_url:
                      fb_link_group:
                      available_duplicate_contacts: 0
                      use_ticket_schema_emails: 0
                      lesson_schema_graph: "[]"
                      use_lesson_schema_graph: 0
                    logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    logo_type: png
                    subway_station:
                    location_name:
                    created_at: '2021-12-31T11:11:57.000000Z'
                    updated_at: '2022-04-05T07:32:06.000000Z'
                    fill_step:
                      id: 1
                      main_setting_step: 1
                      ticket_schema_step: 1
                      mail_test_step: 0
                      register_form_step: 1
                      site_course_step: 1
                      payment_method_step: 1
                      course_id: 2
                      created_at: '2021-12-31T11:11:58.000000Z'
                      updated_at: '2022-04-07T15:19:13.000000Z'
                      promo_codes_step: 0
                      streaming_links_step: 0
                    statistics: []
                    finances: []
                    stream_schemas: []
                    fee: ''
/showProfile:
  displayName: Profile
  description: Get user profile data in LMSka
  get:
    is: [ assets.paging]
    description: Get user profile data in LMSka  
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                id: 45
                first_name: John
                last_name: Doe
                avatar: https://a.lmska.com/storage/users/45/ava123.jpeg
                telephone_code: '380'
                telephone_number: '312312312'
                is_check_in: 1
                is_print_sticker: 1
                telephone_full_number: '380312312312'
                custom_fields:
                courses: []
                company:
                parents: []
                children: []
                email: jd@axonax.com
                role:
                  id: 5
                  name: Student
                  role: student
                permissions:
                - id: 1
                  name: Can see detail of the course
                  permission: can_show_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 2
                  name: Can see all courses
                  permission: can_index_courses
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 3
                  name: Can delete the course
                  permission: can_destroy_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 4
                  name: Can create the new course
                  permission: can_store_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 5
                  name: Can update the existing course
                  permission: can_update_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 8
                  name: Can update profile
                  permission: can_update_profile
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 9
                  name: Can show profile
                  permission: can_show_profile
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 39
                  name: Can store course order
                  permission: can_store_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 40
                  name: Can show course order
                  permission: can_show_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 41
                  name: Can make course order report
                  permission: can_make_course_order_report
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 42
                  name: Can update course order
                  permission: can_update_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 43
                  name: Can destroy course order
                  permission: can_destroy_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 44
                  name: Can index course orders
                  permission: can_index_course_orders
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 45
                  name: Can store promo code
                  permission: can_store_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 46
                  name: Can show promo code
                  permission: can_show_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 47
                  name: Can update promo code
                  permission: can_update_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 48
                  name: Can destroy promo code
                  permission: can_destroy_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 49
                  name: Can index promo codes
                  permission: can_index_promo_code_orders
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                created_at: '2022-03-31T09:20:18.000000Z'
                verified: 1
                mail_credit_balance: 0
                logs: []
                balance_info: []
                scans:
                  data: []
                  pagination:
                    total: 0
                    current_page: 1
                    total_pages: 1
                    count: 0
                    per_page: 50
                u_scanned: []
                u_scanned_by: []
                zones: []
                user_hash:
                promo_code_options: []
                ticket_schemas: []
                quiz_history: []
                coins: 0
                why_rte: 0
                scan_mode: 0
                ban:
                photo_manual: 0
                photo_auto: 0
                storage_capacity: 1073709860
                max_storage_capacity: 1073741824
                chats:
                  data: []
                fee: []
                student_of_lessons:
                  data:
                  - id: 14
                    title: HTML теги (теория)
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 4
                      category: Блок 1
                  - id: 15
                    title: HTML теги форматирования текста
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 4
                      category: Блок 1
                  - id: 16
                    title: Создание скелета HTML документа
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 4
                      category: Блок 1
                  - id: 17
                    title: Установка редактора Brackets
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 4
                      category: Блок 1
                  - id: 18
                    title: Шестой урок
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 5
                      category: Секция 2
                  - id: 19
                    title: Седьмой урок
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 5
                      category: Секция 2
                  - id: 20
                    title: Восьмой урок
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 9
                      category: БОНУС
                  - id: 81
                    title: Что такое билетный оператор
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 83
                    title: Типы билетов в RegToEVENT
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 84
                    title: Апгрейд билета
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 85
                    title: Дополнительные опции
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 86
                    title: Расписание цен
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 87
                    title: Форма регистрации
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 88
                    title: Интеграция формы
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 89
                    title: Оплата билетов
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 90
                    title: Сайт события
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 91
                    title: Оформление билета
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 92
                    title: Промокоды
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 93
                    title: Онлайн трансляции
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 94
                    title: Чат-боты и рассылки
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 95
                    title: Роли пользователей
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 96
                    title: Дополнительные возможности
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 97
                    title: Возможные сценарии
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 98
                    title: Часто задаваемые вопросы
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 106
                    title: Введение
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 4
                      category: Блок 1
                lecturer_of_lessons:
                  data: []
/updateProfile:
  displayName: Update Profile
  description: Update user profile data in LMSka
  put:
    is: [ assets.paging]
    description: Update user profile data in LMSka
    queryParameters: 
      email:
        type: string
        description: Email address
        example: V@rte.im
      telephone_number:
        type: string
        description: Phone number
        example: 312312312
      telephone_code:
        type: string
        description: Phone number
        example: +380
      first_name:
        type: string
        description: First Name
        example: John
      last_name:
        type: string
        description: Last Name
        example: Doe
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                id: 45
                first_name: John
                last_name: Doe
                avatar: https://a.lmska.com/storage/users/45/ava123.jpeg
                telephone_code: '380'
                telephone_number: '312312312'
                is_check_in: 1
                is_print_sticker: 1
                telephone_full_number: '380312312312'
                custom_fields:
                courses: []
                company:
                parents: []
                children: []
                email: jd@axonax.com
                role:
                  id: 5
                  name: Student
                  role: student
                permissions:
                - id: 1
                  name: Can see detail of the course
                  permission: can_show_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 2
                  name: Can see all courses
                  permission: can_index_courses
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 3
                  name: Can delete the course
                  permission: can_destroy_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 4
                  name: Can create the new course
                  permission: can_store_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 5
                  name: Can update the existing course
                  permission: can_update_course
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 8
                  name: Can update profile
                  permission: can_update_profile
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 9
                  name: Can show profile
                  permission: can_show_profile
                  group:
                    id: 2
                    name: Courses
                    group: course
                - id: 39
                  name: Can store course order
                  permission: can_store_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 40
                  name: Can show course order
                  permission: can_show_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 41
                  name: Can make course order report
                  permission: can_make_course_order_report
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 42
                  name: Can update course order
                  permission: can_update_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 43
                  name: Can destroy course order
                  permission: can_destroy_course_order
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 44
                  name: Can index course orders
                  permission: can_index_course_orders
                  group:
                    id: 9
                    name: Course order group
                    group: course_order
                - id: 45
                  name: Can store promo code
                  permission: can_store_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 46
                  name: Can show promo code
                  permission: can_show_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 47
                  name: Can update promo code
                  permission: can_update_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 48
                  name: Can destroy promo code
                  permission: can_destroy_promo_code_order
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                - id: 49
                  name: Can index promo codes
                  permission: can_index_promo_code_orders
                  group:
                    id: 11
                    name: Course promo code group
                    group: course_promo_code
                created_at: '2022-03-31T09:20:18.000000Z'
                verified: 1
                mail_credit_balance: 0
                logs: []
                balance_info: []
                scans:
                  data: []
                  pagination:
                    total: 0
                    current_page: 1
                    total_pages: 1
                    count: 0
                    per_page: 50
                u_scanned: []
                u_scanned_by: []
                zones: []
                user_hash:
                promo_code_options: []
                ticket_schemas: []
                quiz_history: []
                coins: 0
                why_rte: 0
                scan_mode: 0
                ban:
                photo_manual: 0
                photo_auto: 0
                storage_capacity: 1073709860
                max_storage_capacity: 1073741824
                chats:
                  data: []
                fee: []
                student_of_lessons:
                  data:
                  - id: 14
                    title: HTML теги (теория)
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 4
                      category: Блок 1
                  - id: 15
                    title: HTML теги форматирования текста
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 4
                      category: Блок 1
                  - id: 16
                    title: Создание скелета HTML документа
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 4
                      category: Блок 1
                  - id: 17
                    title: Установка редактора Brackets
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 4
                      category: Блок 1
                  - id: 18
                    title: Шестой урок
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 5
                      category: Секция 2
                  - id: 19
                    title: Седьмой урок
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 5
                      category: Секция 2
                  - id: 20
                    title: Восьмой урок
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 9
                      category: БОНУС
                  - id: 81
                    title: Что такое билетный оператор
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 83
                    title: Типы билетов в RegToEVENT
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 84
                    title: Апгрейд билета
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 85
                    title: Дополнительные опции
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 86
                    title: Расписание цен
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 87
                    title: Форма регистрации
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 88
                    title: Интеграция формы
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 89
                    title: Оплата билетов
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 90
                    title: Сайт события
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 91
                    title: Оформление билета
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 92
                    title: Промокоды
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 93
                    title: Онлайн трансляции
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 94
                    title: Чат-боты и рассылки
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 95
                    title: Роли пользователей
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 96
                    title: Дополнительные возможности
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 97
                    title: Возможные сценарии
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 98
                    title: Часто задаваемые вопросы
                    course:
                      id: 7
                      title: Материалы RegToEVENT
                      logo: https://a.lmska.com/storage/logos/courses/7/лого курс.jpg
                    category:
                  - id: 106
                    title: Введение
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 4
                      category: Блок 1
                lecturer_of_lessons:
                  data: []
/attachments:
  displayName: Update Avatar
  description: Update user avatar in LMSka  
  post:
    is: [ assets.paging]
    description: Update user avatar in LMSka 
    queryParameters:
      file:
        type: string
        description: File avatar
        required: true
        example: newAvatar.png  
      user:
        type: bool
        description: Set true if user
        required: true
        example: true   
      user_logo:
        type: bool
        description: Set true if avatar
        required: true
        example: true     
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                path: users/45/ava123.jpeg
                file_name: ava123
                file_size: 10662
                extension: jpeg
                attachment_type_id: 1
                user_id: 45
                updated_at: '2022-04-11T16:10:40.000000Z'
                created_at: '2022-04-11T16:10:40.000000Z'
                id: 138
/courses/{id}/rates:
  displayName: Rates of Course
  description: Get Rates of Course in LMSka  
  get:
    is: [ assets.paging]
    description: Get Rates of Course in LMSka     
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                data:
                - id: 1
                  rate: 4.15
                  additional_text: woah
                  user:
                    id: 4
                    email: d@rte.im
                    role_id: 1
                    avatar: https://a.lmska.com/storage/users/4/Без названия.png
                    first_name: Никита
                    last_name: Депп
                  created_at: '2022-04-13T13:10:08.000000Z'
                - id: 2
                  rate: 5
                  additional_text: |-
                    Очень классный курс. Однозначно рекомендую всем кто хочет что-то изучить :)

                    **Большое спасибо** автору за проделанную работу.
                  user:
                    id: 25
                    email: john@test.lms
                    role_id: 5
                    avatar: https://a.lmska.com/storage/users/25/300_8.jpg
                    first_name: John
                    last_name: Smith
                  created_at: '2022-04-13T15:43:00.000000Z'
/courses/{course_id}/lessons/{lesson_id}/comments:
  displayName: Comments Lesson of Course
  description: Comments Lesson of Course in LMSka  
  get:
    is: [ assets.paging]
    description: Comments Lesson of Course in LMSka     
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                data:
                - id: 3
                  comment_text: Привет Люба
                  created_at: '2022-03-18T13:29:03.000000Z'
                  updated_at: '2022-03-18T13:29:03.000000Z'
                  user:
                    id: 31
                    email: lubashka_l@bigmir.net
                    role_id: 5
                    first_name: Степан
                    last_name:
                    avatar: https://a.lmska.com/storage/default.png
                  childs:
                  - id: 14
                    comment_text: Не трогай Любу !
                    created_at: '2022-04-07T10:35:09.000000Z'
                    updated_at: '2022-04-07T10:35:09.000000Z'
                    user:
                      id: 45
                      email: jd@mail.com
                      role_id: 5
                      first_name: Jenny
                      last_name: Doe
                      avatar: https://a.lmska.com/storage/users/45/image_picker_B99AC0F1-741D-46E7-BFB7-7D6669B56359-34233-0000137A11028F21.jpg
                    parent:
                      id: 3
                      comment_text: Привет Люба
                      created_at: '2022-03-18T13:29:03.000000Z'
                      updated_at: '2022-03-18T13:29:03.000000Z'
                      user:
                        id: 31
                        email: lubashka_l@bigmir.net
                        role_id: 5
                        first_name: Степан
                        last_name:
                        avatar: https://a.lmska.com/storage/default.png
/courses/{course_id}/lessons/{lesson_id}/homeworks:
  displayName: Homework Lesson of Course
  description: Homework Lesson of Course in LMSka  
  get:
    is: [ assets.paging]
    description: Homework Lesson of Course in LMSka     
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              result:
                data:
                - id: 38
                  title: Homework 15
                  type_id: 4
                  lesson:
                    id: 15
                    title: HTML теги форматирования текста
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 15
                      category: Секция 2
                      course_id: 2
                  position: 1
                  start_time: '2022-04-09 12:07:18'
                  end_time: '2021-12-31 00:00:00'
                  body: "<p>Что такое редактор кода и на сколько важны все эти инструменты при разрабокте?</p>"
                  passed: 0
                  mark: 0
                  keys: '[{"value": "Первая часть вопроса"}, {"value": "Вторая часть вопроса"}]'
                  passes: []
                - id: 76
                  title: Homework 15
                  type_id: 3
                  lesson:
                    id: 15
                    title: HTML теги форматирования текста
                    course:
                      id: 2
                      title: Тестовый курс
                      logo: https://a.lmska.com/storage/logos/courses/2/logo.png
                    category:
                      id: 15
                      category: Секция 2
                      course_id: 2
                  position: 1
                  start_time: '2022-04-14 17:14:21'
                  end_time: '2030-12-31 00:00:00'
                  body: ''
                  passed: 1
                  mark: 4
                  keys: "{}"
                  passes:
                  - id: 24
                    homework_id: 76
                    user_id: 45
                    passed_at: '2022-04-14 17:14:49'
                    mark: 4
                    file_path:
