#%RAML 1.0
title: LMSka API
version: 1.0
baseUri: https://a.lmska.com/api
description: Writer by Yaroslav Lukyanchuk

uses:
  assets: assets.lib.raml

/auth:
  displayName: Auth
  description: Auth user in LMSka
  put:
    is: [ assets.paging]
    description: Auth in app
    queryParameters:
      email:
        type: string
        description: Account email
        required: true
        example: V@rte.im
      password:
        type: string
        description: Account password
        required: true
        example: 123456      
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              get-reports:
                success: true
                data:
                  data:
                  - 
                    id: 10
                    title: Demo
                    time_report: '2022-02-22 12:18:13'
                    file: http://127.0.0.1:8000/storage/files/Screenshot 2022-02-22 at 10.12.51_1645537041.png
                    speaker:
                      id: 119
                      user_id: 5
                      event_id: 3200
                      created_at:
                      updated_at:
                      full_name: ''
                  pagination:
                    total: 1
                    total_pages: 1
                    per_page: 2
                    current_page: 1
                    current_per_page: 1
                info: Apk Settings Event Program Reports API
                message: Get Event Program Reports
  